#! /bin/bash
#cd $monk/analysis/newstr/roi
#mkdir $monk/data/cmd
#rm $monk/data/cmd/cmd2_*
#rm $monk/data/cmd/jobid
#cd $monk/analysis/newstr/roi

CMD1_batch=$hr/fs/log_mr/batch_5ttgen
rm -rf $CMD1_batch

for s in `cat /ifs/scratch/pimri/posnerlab/1anal/highrisk/fs/goodsubject.txt`
do

### 5TTGEN
cd /ifs/scratch/pimri/posnerlab/1anal/highrisk/fs/${s}/dmri2
CMD1=$hr/fs/log_mr/cmd.5ttgen.${s}
rm -rf $CMD1
echo "#!/bin/bash
source ~/.bashrc
FREESURFER_HOME=$work/freesurfer_dev/freesurfer
source /ifs/scratch/pimri/posnerlab/freesurfer_dev/freesurfer/FreeSurferEnv.sh
mri_convert ../mri/T1.mgz tmp.nii.gz
flip4fsl tmp.nii.gz T1_flip.nii.gz
mrconvert mr_meanb0.mif.gz mr_meanb0.nii.gz
flirt -in T1_flip.nii.gz -out T1_diff.nii.gz -ref mr_meanb0.nii.gz -applyxfm -init ../dmri/xfms/anat2diff.flt.mat -v
5ttgen fsl T1_diff.nii.gz 5tt.mif.gz -force -nthreads 12
mrconvert 5tt.mif.gz 5tt.nii.gz -force
5tt2gmwmi 5tt.mif.gz 5tt_gmwmi_mask.mif.gz

############
labelconvert ../mri/aparc+aseg_orient_diffusion_1mm.nii.gz $FREESURFER_HOME/FreeSurferColorLUT.txt /ifs/scratch/pimri/posnerlab/app/mrtrix3/src/connectome/tables/fs_default.txt nodes.mif.gz -force
#labelsgmfix nodes.mif.gz T1_diff.nii.gz fs_default.txt nodes_fixSGM.mif.gz -sgm_amyg_hipp -premasked -verbose -nthreads 12
############
" >$CMD1


#batch 
echo $CMD1 >> $CMD1_batch
done

#prepid=`$code/fsl_sub_hpc -T 60 -M 0.3G -l $hr/fs/log_mr -s smp,12 -t $CMD1`

for s in `cat /ifs/scratch/pimri/posnerlab/1anal/highrisk/fs/goodsubject.txt`
do
CMD2=$hr/fs/log_mr/cmd.tckgensift.${s}
rm -rf $CMD2

echo "#!/bin/bash
source ~/.bashrc
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=12
echo NOW WARPING FOR SUBJECT ${s}
#cd /ifs/scratch/pimri/posnerlab/1anal/Monk/fs_new/${s}/dmri
#ref=/ifs/scratch/pimri/posnerlab/1anal/Monk/template/infant-neo-withCerebellum.nii


cd /ifs/scratch/pimri/posnerlab/1anal/highrisk/fs/${s}/dmri2

### FREE UP SOME SPACE

## FREEING UP SOME SPACE
#gzip -f -v *mif 
#rm -f mr_fod_tckgen_*.tck



#if [ -e /ifs/scratch/pimri/posnerlab/1anal/Monk/analysis/newstr/vbm/struc/${s}_str_nu_brain.nii.gz ] ; then 
   
## step1. mni to str
#imcp /ifs/scratch/pimri/posnerlab/1anal/Monk/analysis/newstr/vbm/struc/${s}_str_nu_brain.nii.gz  ./str.nii.gz
#imcp /ifs/scratch/pimri/posnerlab/1anal/Monk/template/infant-neo-withCerebellum.nii ./mni.nii && gzip -f mni.nii
#imcp /ifs/scratch/pimri/posnerlab/1anal/Monk/template/infant-neo-aal.nii ./mni_aal.nii && gzip -f mni_aal.nii

#ANTS 3 -m PR[str.nii.gz,mni.nii.gz,1,2] -i 50x20x10 -o mni2str_synants.nii.gz -t SyN[0.3] -r Gauss[3,0]

#WarpImageMultiTransform 3 mni.nii.gz mni2str_warped_synants.nii.gz -R str.nii.gz mni2str_synantsWarp.nii.gz mni2str_synantsAffine.txt
#WarpImageMultiTransform 3 mni_aal.nii.gz mni_aal2str_synants.nii.gz -R str.nii.gz mni2str_synantsWarp.nii.gz mni2str_synantsAffine.txt --use-NN


## step2. str to diff
#ANTS 3 -m PR[lowb_brain.nii.gz,str.nii.gz,1,2] -i 50x20x10 -o str2diff_synants.nii.gz -t SyN[0.3] -r Gauss[3,0]
#WarpImageMultiTransform 3 str.nii.gz str2diff_warped_synants.nii.gz -R lowb_brain.nii.gz str2diff_synantsWarp.nii.gz str2diff_synantsAffine.txt
#WarpImageMultiTransform 3 mni_aal2str_synants.nii.gz mni_aal2diff_warped_synants.nii.gz -R lowb_brain.nii.gz str2diff_synantsWarp.nii.gz str2diff_synantsAffine.txt --use-NN


## step3. MNI2DIFF
## ALTERNATIVE MNI2DIFF
#ANTS 3 -m PR[lowb_brain.nii.gz,mni.nii.gz,1,2] -i 100x100x20 -o mni2diff_synants.nii.gz -t SyN[0.3] -r Gauss[2,0]
#WarpImageMultiTransform 3 mni.nii.gz mni2diff_warped_synants.nii.gz -R lowb_brain.nii.gz mni2diff_synantsWarp.nii.gz mni2diff_synantsAffine.txt
#WarpImageMultiTransform 3 mni_aal.nii.gz mni_aal2diff_warped_synants.nii.gz -R lowb_brain.nii.gz mni2diff_synantsWarp.nii.gz mni2diff_synantsAffine.txt --use-NN


#flirt -in mni -ref lowb_brain -out mni2diff_flirt -omat mni2diff.mat -v
#flirt -in mni_aal -ref lowb_brain -out mni_aal2diff_flirt -applyxfm -init mni2diff.mat -v -interp nearestneighbour

#ANTS 3 -m PR[lowb_brain.nii.gz,mni2diff_flirt,1,2] -i 100x100x20 -o mni2diff_synants.nii.gz -t SyN[0.3] -r Gauss[2,0]
#WarpImageMultiTransform 3 mni2diff_flirt.nii.gz mni2diff_warped_synants.nii.gz -R lowb_brain.nii.gz mni2diff_synantsWarp.nii.gz mni2diff_synantsAffine.txt
#WarpImageMultiTransform 3 mni_aal2diff_flirt.nii.gz mni_aal2diff_warped_synants.nii.gz -R lowb_brain.nii.gz mni2diff_synantsWarp.nii.gz mni2diff_synantsAffine.txt --use-NN

#else echo no good str exist. use the atlas

#fi

#labelconvert mni_aal2diff_warped_synants.nii.gz $monk/data/mr_roi_lut.txt $monk/data/mr_roi_lut.txt mr_parcels.mif -nthreads 12 -force
#bet2 lowb lowb_brain -m  
#gzip -d -f -v mr_fod.mif.gz



#tckgen WM_FODs.mif.gz 1M.tck -act 5tt.mif.gz -backtrack -crop_at_gmwmi -rk4 -seed_dynamic WM_FODs.mif.gz -maxlength 250 -number 1M -force -nthreads 12


#dwi2fod csd mr_dwi_denoised_preproc_biasCorr_reduced.mif* ../../group_average_response.txt mr_fod_group_response.mif.gz -mask mr_dilate_mask.mif -force
if [ -e mr_track_10M_SIFT.tck ] ; then echo SIFT is already done
else tckgen WM_FODs.mif.gz mr_track_100M.tck -act 5tt.mif.gz -backtrack -crop_at_gmwmi -seed_dynamic WM_FODs.mif.gz -maxlength 250 -minlength 30 -number 100M -force -nthreads 12


#-seed_image mr_parcels.mif* -mask lowb_brain_mask.nii.gz -number 100M -maxlength 100 -force -nthreads 12 && echo tckgen done***************
tcksift -act 5tt.mif.gz mr_track_100M.tck WM_FODs.mif.gz mr_track_10M_SIFT.tck -term_number 10M -force -nthreads 12 && echo sift done*******
fi 

if [ -e mr_track_10M_SIFT.tck ] ; then rm mr_track_100M.tck 
else echo SIFT WAS NOT SUCCESSFUL
fi

tck2connectome -force -zero_diagonal -nthreads 12 mr_track_10M_SIFT.tck nodes.mif.gz mr_sift_10M_connectome_count.csv 
tck2connectome -force -zero_diagonal -scale_length -stat_edge mean -nthreads 12 mr_track_10M_SIFT.tck nodes.mif.gz mr_sift_10M_connectome_length.csv 
tck2connectome -force -zero_diagonal -scale_invnodevol -nthreads 12 mr_track_10M_SIFT.tck nodes.mif.gz mr_sift_10M_connectome_volumeadjusted.csv 

echo END OF TCKGEN AND SIFT

#gzip -f -v mr_fod_3M_SIFT.tck 
#gzip -f -v mr_fod.mif




#### GENERATING CONNECTOME

" > $CMD2

chmod +x $CMD2
#$code/fsl_sub_hpc_6 -s smp,12 -j $prepid -l $hr/fs/log_mr $CMD2
#$code/fsl_sub_hpc_36 $monk/data/cmd/cmd2_${s}  
#echo $jobid >> $monk/data/cmd/jobid
#$code/fsl_sub_hpc_3 -N connectome -s smp,12 -j $prepid -l $hr/fs/log_mr $CMD2 

  
#fi
#echo "cd $monk/analysis/dti/${s}/dmri && convert_xfm -omat mni2diff.mat -concat str2diff.mat mni2str.mat && convert_xfm -omat diff2mni.mat -inverse mni2diff.mat" >> $monk/cmd
done 
#cd $monk
#$code/fsl_sub_hpc_6 -T 1440 -N warp -t $monk/cmd
